#!/bin/sh
#
# Copyright (c) 2013 IBM Corporation
# All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this
# distribution, and is available at http://www.eclipse.org/legal/epl-v10.html
#
OS_DISTRIBUTOR=`lsb_release -a 2>/dev/null | grep Distributor | awk '{print $3}'`
echo $OS_DISTRIBUTOR
